# Generated by Django 3.0.6 on 2020-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, verbose_name='Product ID')),
                ('opinion_id', models.CharField(max_length=10, unique=True, verbose_name='Opinion ID')),
                ('author', models.CharField(max_length=10, verbose_name='Author')),
                ('recomendation', models.NullBooleanField(default=None, verbose_name='User recomendation')),
                ('stars', models.FloatField(verbose_name='Score')),
                ('content', models.TextField(verbose_name='Content')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='Cons')),
                ('pros', models.TextField(blank=True, null=True, verbose_name='Pros')),
                ('useful', models.PositiveSmallIntegerField(default=0, verbose_name='Useful')),
                ('useless', models.PositiveSmallIntegerField(default=0, verbose_name='Useless')),
                ('opinion_date', models.DateTimeField(verbose_name='Opinion date')),
                ('purchase_date', models.DateTimeField(verbose_name='Purchase date')),
            ],
        ),
    ]
