# Generated by Django 3.0.7 on 2020-06-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0002_auto_20200531_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='opinionmodel',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper_app.ProductModel', verbose_name='Product'),
        ),
    ]
