# Generated by Django 3.0.7 on 2020-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0003_auto_20200606_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.CharField(max_length=8, verbose_name='Product ID'),
        ),
    ]
