# Generated by Django 3.0.7 on 2020-06-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0004_auto_20200606_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinionmodel',
            old_name='product_id',
            new_name='product',
        ),
    ]
