# Generated by Django 3.0.7 on 2020-06-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0005_auto_20200606_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default='f', max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
