# Generated by Django 3.0.7 on 2020-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0007_auto_20200606_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionmodel',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase date'),
        ),
    ]
