# Generated by Django 3.0.7 on 2020-06-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0008_auto_20200606_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='Product ID'),
        ),
    ]
